// assets.js — chemins des images (rangs, avatars, décorations).
// Charge AVANT app.js. Variables partagées au scope global du script.

// ─── Assets de rang, par palier de base ───
// Collection complète : bois → challenger.
// Pour ajouter/modifier un palier, copier un bloc et changer le nom + les chemins.
const RANK_ASSETS_DESKTOP = {
  bois: {
    emblem:        'assets/bois_emblem.png',
    banner:        'assets/bois_banner.png',
    player_frame:  'assets/bois_frame.png',
    profile_frame: 'assets/bois_frame.png',
  },
  bronze: {
    emblem:        'assets/bronze_emblem.png',
    banner:        'assets/bronze_banner.png',
    player_frame:  'assets/bronze_frame.png',
    profile_frame: 'assets/bronze_frame.png',
  },
  argent: {
    emblem:        'assets/argent_emblem.png',
    banner:        'assets/argent_banner.png',
    player_frame:  'assets/argent_frame.png',
    profile_frame: 'assets/argent_frame.png',
  },
  or: {
    emblem:        'assets/or_emblem.png',
    banner:        'assets/or_banner.png',
    player_frame:  'assets/or_frame.png',
    profile_frame: 'assets/or_frame.png',
  },
  platine: {
    emblem:        'assets/platine_emblem.png',
    banner:        'assets/platine_banner.png',
    player_frame:  'assets/platine_frame.png',
    profile_frame: 'assets/platine_frame.png',
  },
  diamant: {
    emblem:        'assets/diamant_emblem.png',
    banner:        'assets/diamant_banner.png',
    player_frame:  'assets/diamant_frame.png',
    profile_frame: 'assets/diamant_frame.png',
  },
  maitre: {
    emblem:        'assets/maitre_emblem.png',
    banner:        'assets/maitre_banner.png',
    player_frame:  'assets/maitre_frame.png',
    profile_frame: 'assets/maitre_frame.png',
  },
  grandmaitre: {
    emblem:        'assets/grandmaitre_emblem.png',
    banner:        'assets/grandmaitre_banner.png',
    player_frame:  'assets/grandmaitre_frame.png',
    profile_frame: 'assets/grandmaitre_frame.png',
  },
  challenger: {
    emblem:        'assets/challenger_emblem.png',
    banner:        'assets/challenger_banner.png',
    player_frame:  'assets/challenger_frame.png',
    profile_frame: 'assets/challenger_frame.png',
  },
};

const RANK_ASSETS_MOBILE = {
  bois: {
    emblem:        'assets/bois_emblem.png',
    banner:        'assets/bois_banner.png',
    player_frame:  'assets/bois_frame.png',
    profile_frame: 'assets/bois_frame.png',
  },
  bronze: {
    emblem:        'assets/bronze_emblem.png',
    banner:        'assets/bronze_banner.png',
    player_frame:  'assets/bronze_frame.png',
    profile_frame: 'assets/bronze_frame.png',
  },
  argent: {
    emblem:        'assets/argent_emblem.png',
    banner:        'assets/argent_banner.png',
    player_frame:  'assets/argent_frame.png',
    profile_frame: 'assets/argent_frame.png',
  },
  or: {
    emblem:        'assets/or_emblem.png',
    banner:        'assets/or_banner.png',
    player_frame:  'assets/or_frame.png',
    profile_frame: 'assets/or_frame.png',
  },
  platine: {
    emblem:        'assets/platine_emblem.png',
    banner:        'assets/platine_banner.png',
    player_frame:  'assets/platine_frame.png',
    profile_frame: 'assets/platine_frame.png',
  },
  diamant: {
    emblem:        'assets/diamant_emblem.png',
    banner:        'assets/diamant_banner.png',
    player_frame:  'assets/diamant_frame.png',
    profile_frame: 'assets/diamant_frame.png',
  },
  maitre: {
    emblem:        'assets/maitre_emblem.png',
    banner:        'assets/maitre_banner.png',
    player_frame:  'assets/maitre_frame.png',
    profile_frame: 'assets/maitre_frame.png',
  },
  grandmaitre: {
    emblem:        'assets/grandmaitre_emblem.png',
    banner:        'assets/grandmaitre_banner.png',
    player_frame:  'assets/grandmaitre_frame.png',
    profile_frame: 'assets/grandmaitre_frame.png',
  },
  challenger: {
    emblem:        'assets/challenger_emblem.png',
    banner:        'assets/challenger_banner.png',
    player_frame:  'assets/challenger_frame.png',
    profile_frame: 'assets/challenger_frame.png',
  },
};

// Fond derrière l'avatar (aucun pour l'instant → fond teinté par défaut).
const RANK_AVATAR_BG = {};

// Petites icônes de rang (classement, listes, aperçus de points).
const RANK_EMBLEMS = {
  bois:       'assets/bois_icon.png',
  bronze:     'assets/bronze_icon.png',
  argent:     'assets/argent_icon.png',
  or:         'assets/or_icon.png',
  platine:    'assets/platine_icon.png',
  diamant:    'assets/diamant_icon.png',
  maitre:     'assets/maitre_icon.png',
  grandmaitre:'assets/grandmaitre_icon.png',
  challenger: 'assets/challenger_icon.png',
};

// ─── Avatars de profil ───
const AVATARS = [
  { id: 1, label: 'Le Gardien Céleste', src: 'assets/avatar1.webp' },
  { id: 2, label: 'La Reine Pirate', src: 'assets/avatar2.webp' },
  { id: 3, label: 'Le Paladin', src: 'assets/avatar3.webp' },
  { id: 4, label: 'La Steampunk', src: 'assets/avatar4.webp' },
  { id: 5, label: 'Le Mage', src: 'assets/avatar5.webp' },
  { id: 6, label: 'Le Capitaine de Guilde', src: 'assets/avatar6.webp' },
  { id: 7, label: 'Le Samouraï', src: 'assets/avatar7.webp' },
  { id: 8, label: 'Le Viking Berserker', src: 'assets/avatar8.webp' },
  { id: 9, label: 'La Reine des Neiges', src: 'assets/avatar9.webp' },
  { id: 10, label: 'L\'Assassin des Ombres', src: 'assets/avatar10.webp' },
  { id: 11, label: 'La Maîtresse du Jeu', src: 'assets/avatar11.webp' },
  { id: 12, label: 'Le Roi Dragon', src: 'assets/avatar12.webp' },
  { id: 13, label: 'L\'Alchimiste', src: 'assets/avatar13.webp' },
  { id: 14, label: 'L\'Architecte', src: 'assets/avatar14.webp' },
  { id: 15, label: 'La Nécromancienne', src: 'assets/avatar15.webp' },
  { id: 16, label: 'Le Pirate', src: 'assets/avatar16.webp' },
  { id: 17, label: 'La Druidesse', src: 'assets/avatar17.webp' },
  { id: 18, label: 'Le Marchand', src: 'assets/avatar18.webp' },
  { id: 19, label: 'La Guerrière', src: 'assets/avatar19.webp' },
  { id: 20, label: 'Le Grand Stratège', src: 'assets/avatar20.webp' },
  { id: 21, label: 'Le Roi-Foudre', src: 'assets/avatar21.webp', reqAch: 'rank_diamant_1' },
  { id: 22, label: 'Le Gardien sylvestre', src: 'assets/avatar22.webp', reqAch: 'bois_30j' },
  { id: 23, label: 'Sandworm King', src: 'assets/avatar23.webp', reqAch: 'dune_win_10' },
  { id: 24, label: 'The Spice Sovereign', src: 'assets/avatar24.webp', reqAch: 'dune_win_20' },
  { id: 25, label: 'Le Roi des Abysses', src: 'assets/avatar25.webp', reqAch: 'skullking_win_50' },
  { id: 26, label: 'L\'Impératrice Stellaire',   src: 'assets/avatar26.webp', reqAch: 'iaww_win_15' },
  { id: 27, label: 'L\'Architecte d\'Akropolis', src: 'assets/avatar27.webp', reqAch: 'akropolis_win_15' },
  { id: 28, label: 'La Magnat de Birmingham',     src: 'assets/avatar28.webp', reqAch: 'brass_play_10' },
  { id: 29, label: 'Le Roi de Divinus',           src: 'assets/avatar29.webp', reqAch: 'divinus_win_10' },
  { id: 30, label: 'La Reine de Divinus',         src: 'assets/avatar30.webp', reqAch: 'divinus_win_10' },
  { id: 31, label: 'Le Roi de Cardia',            src: 'assets/avatar31.webp', reqAch: 'cardia_win_75' },
  { id: 32, label: 'Le Daimyo de Cardia',         src: 'assets/avatar32.webp', reqAch: 'cardia_win_50' },
  { id: 33, label: 'Le Seigneur de Cardia',       src: 'assets/avatar33.webp', reqAch: 'cardia_win_25' },
  { id: 34, label: 'Le Lapin Jardinier',          src: 'assets/avatar34.webp', reqAch: 'harmonies_play_15' },
  { id: 35, label: 'Le Cerf des Saisons',         src: 'assets/avatar35.webp', reqAch: 'harmonies_win_15' },
  { id: 36, label: 'La Grue Légendaire',          src: 'assets/avatar36.webp', reqAch: 'harmonies_win_30' },
  { id: 37, label: 'Le Dragon de Jade',           src: 'assets/avatar37.webp', reqAch: 'mytho_play_10' },
  { id: 38, label: 'La Déesse au Lotus',          src: 'assets/avatar38.webp', reqAch: 'mytho_play_20' },
  { id: 39, label: 'La Reine du Nil',             src: 'assets/avatar39.webp', reqAch: 'mytho_play_30' },
  { id: 40, label: 'Humain Zenith',               src: 'assets/avatar40.webp', reqAch: 'zenith_play_10' },
  { id: 41, label: 'Humain Zenith Prime',         src: 'assets/avatar41.webp', reqAch: 'zenith_win_10' },
  { id: 42, label: 'Robot Zenith',                src: 'assets/avatar42.webp', reqAch: 'zenith_play_20' },
  { id: 43, label: 'Robot Zenith Prime',          src: 'assets/avatar43.webp', reqAch: 'zenith_win_20' },
  { id: 44, label: 'Animal Zenith',               src: 'assets/avatar44.webp', reqAch: 'zenith_play_30' },
  { id: 45, label: 'Animal Zenith Prime',         src: 'assets/avatar45.webp', reqAch: 'zenith_win_30' },
  { id: 46, label: 'Canard Toy Battle',           src: 'assets/avatar46.webp', reqAch: 'toybattle_play_15' },
  { id: 47, label: 'Canard Toy Battle Prime',     src: 'assets/avatar47.webp', reqAch: 'toybattle_win_15' },
  { id: 48, label: 'Chevalier Toy Battle Prime',  src: 'assets/avatar48.webp', reqAch: 'toybattle_win_50' }
];

// ─── Cadres cosmétiques déblocables par succès ───
// Chaque cadre a son trou (FRAME_HOLES inline) et un succès requis (reqAch).
// frame = null/0 sur le joueur → cadre du rang par défaut.
const FRAMES = [
  { id: 2, label: 'Le Roi des Abysses', src: 'assets/skullking_frame.png',
    hole: { top: 26, left: 31, size: 88, top_m: 14, left_m: 17, size_m: 47 },
    reqAch: 'skullking_win_50' },
  { id: 3, label: 'Les Sept Merveilles', src: 'assets/7wonders_frame.png',
    hole: { top: 40, left: 38, size: 74, top_m: 21, left_m: 20, size_m: 39 },
    reqAch: '7w_win_25' },
  { id: 4, label: 'Akropolis', src: 'assets/akropolis_frame.png',
    hole: { top: 19, left: 19, size: 112, top_m: 10, left_m: 10, size_m: 60 },
    reqAch: 'akropolis_win_15' },
  { id: 5, label: 'Brass Birmingham', src: 'assets/brass_frame.png',
    hole: { top: 20, left: 30, size: 89, top_m: 11, left_m: 16, size_m: 47 },
    reqAch: 'brass_win_15' },
  { id: 6, label: 'Panthéon Grec', src: 'assets/mytho_grec_frame.png',
    hole: { top: 34, left: 33, size: 84, top_m: 18, left_m: 18, size_m: 45 },
    reqAch: 'mytho_play_10' },
  { id: 7, label: 'Panthéon Nordique', src: 'assets/mytho_nordique_frame.png',
    hole: { top: 23, left: 31, size: 87, top_m: 12, left_m: 17, size_m: 46 },
    reqAch: 'mytho_play_20' },
  { id: 8, label: 'Panthéon Aztèque', src: 'assets/mytho_azteque_frame.png',
    hole: { top: 27, left: 32, size: 85, top_m: 15, left_m: 17, size_m: 46 },
    reqAch: 'mytho_play_30' },
  { id: 9, label: 'Citadelle Toy Battle', src: 'assets/toybattle_player_frame.png',
    hole: { top: 18, left: 20, size: 109, top_m: 10, left_m: 11, size_m: 58 },
    reqAch: 'toybattle_play_30' },
  { id: 10, label: 'Couronne Toy Battle', src: 'assets/toybattle_crown_frame.png',
    hole: { top: 27, left: 26, size: 98, top_m: 14, left_m: 14, size_m: 52 },
    reqAch: 'toybattle_win_50' }
];

// ─── Fonds de carte déblocables par succès ───
// cardbg = null/0 sur le joueur → fond uni par défaut.
const BACKGROUNDS = [
  { id: 1, label: 'Shai-Hulud', src: 'assets/bg_dune.webp', reqAch: 'dune_win_20' },
  { id: 2, label: 'Cité des Merveilles', src: 'assets/bg_7wonders.webp', reqAch: '7w_play_15' },
  { id: 3, label: 'L\'Arbre-Monde', src: 'assets/bg_foret.webp', reqAch: 'foret_play_15' },
  { id: 4, label: 'Un Monde Merveilleux', src: 'assets/bg_iaww.webp', reqAch: 'iaww_win_15' },
  { id: 5, label: 'Île de Catane', src: 'assets/bg_catan.webp', reqAch: 'catan_play_15' },
  { id: 6, label: 'Night City', src: 'assets/bg_cyberpunk.webp', reqAch: 'cyberpunk_play_10' },
  { id: 7, label: 'Sanctuaire d\'Harmonies', src: 'assets/bg_harmonies.webp', reqAch: 'harmonies_play_15' },
  { id: 8, label: 'Cité de Zenith', src: 'assets/bg_zenith.webp', reqAch: 'zenith_play_50' },
  { id: 9, label: 'Champ de bataille Toy Battle', src: 'assets/bg_toybattle.webp', reqAch: 'toybattle_win_15' },
  { id: 10, label: 'Vallée de l\'Éternité', src: 'assets/bg_vale.webp', reqAch: 'vale_play_25' },
  { id: 11, label: 'Les Vitraux de Sintra',     src: 'assets/bg_azul.webp',      reqAch: 'azul_play_15' },
  { id: 12, label: 'Le Parc d\'Ark Nova',       src: 'assets/bg_arknova.webp',   reqAch: 'arknova_play_15' },
  { id: 13, label: 'La Cité Stellaire d\'Arcs', src: 'assets/bg_arcs.webp',      reqAch: 'arcs_play_15' },
  { id: 14, label: 'Les Hauteurs d\'Akropolis', src: 'assets/bg_akropolis.webp', reqAch: 'akropolis_play_15' },
  { id: 15, label: 'Le Palais des Abysses',     src: 'assets/bg_abyss.webp',     reqAch: 'abyss_play_15' },
  { id: 16, label: 'Les Cités Royales',          src: 'assets/bg_citesroyales.webp', reqAch: 'citesroyales_play_15' },
  { id: 17, label: 'La Cité des Intrigues',      src: 'assets/bg_citadelles.webp',   reqAch: 'citadelles_play_15' },
  { id: 18, label: 'Le Royaume Combo',           src: 'assets/bg_chateaucombo.webp', reqAch: 'chateaucombo_play_15' },
  { id: 19, label: 'Le Château Blanc',           src: 'assets/bg_chateaublanc.webp', reqAch: 'chateaublanc_play_15' },
  { id: 20, label: 'Les Remparts de Carcassonne',src: 'assets/bg_carcassonne.webp',  reqAch: 'carcassonne_play_15' },
  { id: 21, label: 'Les Forges de Birmingham',   src: 'assets/bg_brass.webp',        reqAch: 'brass_play_15' },
  { id: 22, label: 'La Forêt-Noire',             src: 'assets/bg_blackforest.webp',  reqAch: 'blackforest_play_15' },
  { id: 23, label: 'Le Grand Barrage',           src: 'assets/bg_barrage.webp',      reqAch: 'barrage_play_15' },
  { id: 24, label: 'Les Terres de Dewan',        src: 'assets/bg_dewan.webp',        reqAch: 'dewan_play_15' },
  { id: 25, label: 'L\'Île Maudite',             src: 'assets/bg_deadcells.webp',    reqAch: 'deadcells_play_15' },
  { id: 26, label: 'L\'Archipel de Darwin',      src: 'assets/bg_darwins.webp',      reqAch: 'darwins_play_15' },
  { id: 27, label: 'Néons de Night City',        src: 'assets/bg_cybertcg.webp',     reqAch: 'cybertcg_play_15' },
  { id: 28, label: 'La Salle du Trône',          src: 'assets/bg_courtisans.webp',   reqAch: 'courtisans_play_15' },
  { id: 29, label: 'L\'Aube des Civilisations',  src: 'assets/bg_civolution.webp',   reqAch: 'civolution_play_15' },
  { id: 30, label: 'Les Royaumes Éternels',      src: 'assets/bg_eternaldecks.webp',  reqAch: 'eternaldecks_play_15' },
  { id: 31, label: 'Les Eaux Profondes',         src: 'assets/bg_endeavor.webp',      reqAch: 'endeavor_play_15' },
  { id: 32, label: 'La Terre du Milieu',         src: 'assets/bg_terredumilieu.webp', reqAch: 'terredumilieu_play_15' },
  { id: 33, label: 'Le Conseil des Mages',       src: 'assets/bg_cardia.webp',        reqAch: 'cardia_win_25' },
  { id: 34, label: 'La Vallée des Cerisiers',    src: 'assets/bg_dorfromantik.webp',  reqAch: 'dorfromantik_play_15' },
  { id: 35, label: 'Le Panthéon de Divinus',     src: 'assets/bg_divinus.webp',       reqAch: 'divinus_win_10' },
  { id: 36, label: 'La Table du Royaume',        src: 'assets/bg_dilemmeduroi.webp',  reqAch: 'dilemmeduroi_play_15' },
  { id: 37, label: 'La Forge des Dieux',         src: 'assets/bg_diceforge.webp',     reqAch: 'diceforge_play_15' },
  { id: 38, label: 'Les Lunes Lointaines',       src: 'assets/bg_faraway.webp',       reqAch: 'faraway_play_15' },
  { id: 39, label: 'L\'Arbre d\'Everdell',       src: 'assets/bg_everdell.webp',      reqAch: 'everdell_play_15' },
  { id: 40, label: 'Le Crépuscule d\'Automne',   src: 'assets/bg_evenfall.webp',      reqAch: 'evenfall_play_15' },
  { id: 41, label: 'Le Cristal d\'Éternité',     src: 'assets/bg_eternitium.webp',    reqAch: 'eternitium_play_15' },
  { id: 42, label: 'La Vallée Fleurie',          src: 'assets/bg_flowers.webp',       reqAch: 'flowers_play_15' },
  { id: 43, label: 'Le Port d\'Edo',             src: 'assets/bg_iki.webp',           reqAch: 'iki_play_15' },
  { id: 44, label: 'L\'Olympe Céleste',          src: 'assets/bg_hybris.webp',        reqAch: 'hybris_play_15' },
  { id: 45, label: 'Les Royaumes en Guerre',     src: 'assets/bg_gwent.webp',         reqAch: 'gwent_play_15' },
  { id: 46, label: 'La Cité Sombre',             src: 'assets/bg_gloomhaven.webp',    reqAch: 'gloomhaven_play_15' },
  { id: 47, label: 'La Croisière Galactique',    src: 'assets/bg_galacticcruise.webp', reqAch: 'galacticcruise_play_15' },
  { id: 48, label: 'La Cour du Royaume',         src: 'assets/bg_foracrown.webp',      reqAch: 'foracrown_play_15' },
  { id: 49, label: 'La Forêt Vivante',           src: 'assets/bg_livingforest.webp',      reqAch: 'livingforest_play_15' },
  { id: 50, label: 'La Villa de la Famiglia',    src: 'assets/bg_lafamiglia.webp',        reqAch: 'lafamiglia_play_15' },
  { id: 51, label: 'Le Royaume de Dominion',     src: 'assets/bg_dominion.webp',          reqAch: 'dominion_play_15' },
  { id: 52, label: 'La Bataille de Hoth',        src: 'assets/bg_hoth.webp',              reqAch: 'hoth_play_15' },
  { id: 53, label: 'L\'Ombre du Kraken',         src: 'assets/bg_kraken.webp',            reqAch: 'kraken_play_15' },
  { id: 54, label: 'Paris 1920',                 src: 'assets/bg_kronologicparis.webp',   reqAch: 'kronologic_play_5' },
  { id: 55, label: 'Les Cimes de Cuzco',         src: 'assets/bg_kronologiccuzco.webp',   reqAch: 'kronologic_play_10' },
  { id: 56, label: 'Les Jardins de Babylone',    src: 'assets/bg_kronologicbabylon.webp', reqAch: 'kronologic_play_15' },
  { id: 57, label: 'La Forge d\'Ironwood',       src: 'assets/bg_ironwood.webp',          reqAch: 'ironwood_play_15' },
  { id: 58, label: 'Réglez vos comptes !',       src: 'assets/bg_now.webp',         reqAch: 'now_play_15' },
  { id: 59, label: 'La Taverne de Nidavellir',   src: 'assets/bg_nidavellir.webp',  reqAch: 'nidavellir_play_15' },
  { id: 60, label: 'Le Vaisseau Nemesis',        src: 'assets/bg_nemesis.webp',     reqAch: 'nemesis_play_15' },
  { id: 61, label: 'Les Ruines de Narak',        src: 'assets/bg_narak.webp',       reqAch: 'narak_play_15' },
  { id: 62, label: 'L\'Empire du Soleil Levant', src: 'assets/bg_naishi.webp',      reqAch: 'naishi_play_15' },
  { id: 63, label: 'L\'Arbre des Mythes',        src: 'assets/bg_mytho.webp',       reqAch: 'mytho_play_20' },
  { id: 64, label: 'La Colonie Lunaire',         src: 'assets/bg_mooncolony.webp',  reqAch: 'mooncolony_play_15' },
  { id: 65, label: 'La Tour Monumentale',        src: 'assets/bg_monumental.webp',  reqAch: 'monumental_play_15' },
  { id: 66, label: 'La Baie de Maracaïbo',       src: 'assets/bg_maracaibo.webp',   reqAch: 'maracaibo_play_15' }
];

// ─── Images décoratives ───
const DECO_IMGS = [
  'assets/deco_imgs.png',
  'assets/deco_imgs_2.png',
  'assets/deco_imgs_3.png',
  'assets/deco_imgs_4.png',
  'assets/deco_imgs_5.png',
  'assets/deco_imgs_6.png',
  'assets/deco_imgs_7.png',
  'assets/deco_imgs_8.png',
  'assets/deco_imgs_9.png',
  'assets/deco_imgs_10.png',
  'assets/deco_imgs_11.png',
  'assets/deco_imgs_12.png',
  'assets/deco_imgs_13.png',
  'assets/deco_imgs_14.png',
  'assets/deco_imgs_15.png',
  'assets/deco_imgs_16.png',
  'assets/deco_imgs_17.png',
  'assets/deco_imgs_18.png',
  'assets/deco_imgs_19.png',
  'assets/deco_imgs_20.png',
  'assets/deco_imgs_21.png',
  'assets/deco_imgs_22.png',
  'assets/deco_imgs_23.png',
  'assets/deco_imgs_24.png',
  'assets/deco_imgs_25.png',
  'assets/deco_imgs_26.png',
  'assets/deco_imgs_27.png',
  'assets/deco_imgs_28.png',
  'assets/deco_imgs_29.png',
  'assets/deco_imgs_30.png',
  'assets/deco_imgs_31.png',
  'assets/deco_imgs_32.png',
];

// ─── Titres équipables (affichés sous le pseudo) ───
// reqAch : id d'un succès (ACHIEVEMENTS dans app.js). null = débloqué d'office.
const TITLES = [
  { id: 1,  label: 'Le Stratège',               icon: '♟️', reqAch: 'wins_10' },
  { id: 2,  label: 'Vétéran des Tables',        icon: '🎲', reqAch: 'games_50' },
  { id: 3,  label: 'Centurion',                 icon: '⚔️', reqAch: 'wins_100' },
  { id: 4,  label: "L'Inarrêtable",             icon: '🔥', reqAch: 'streak_5' },
  { id: 5,  label: 'La Légende',                icon: '🌟', reqAch: 'streak_10' },
  { id: 6,  label: 'Éclat de Diamant',          icon: '💎', reqAch: 'rank_diamant' },
  { id: 7,  label: 'Le Roi de Catan',           icon: '🐑', reqAch: 'catan_play_15' },
  { id: 8,  label: 'Magnat de Birmingham',      icon: '🏭', reqAch: 'brass_win_15' },
  { id: 9,  label: "Architecte d'Akropolis",    icon: '🏛️', reqAch: 'akropolis_win_15' },
  { id: 10, label: 'Âme des Harmonies',         icon: '🦌', reqAch: 'harmonies_win_15' },
  { id: 11, label: 'Gardien des Mythes',        icon: '🐉', reqAch: 'mytho_play_20' },
  { id: 12, label: 'Étoile du Zénith',          icon: '✨', reqAch: 'zenith_win_20' },
  { id: 13, label: 'Seigneur de Cardia',        icon: '🃏', reqAch: 'cardia_win_25' },
  { id: 14, label: 'Maître des Jouets',         icon: '🧸', reqAch: 'toybattle_win_15' },
];
